### PR TITLE
Allow overriding architecture and runtime during `dnvm use`

### LINKED ISSUE #405: dnvm use default -r coreclr does not work
default is 1.0.0-beta8-15120 mono
use default -r coreclr should try to use 1.0.0-beta8-15120 coreclr but it just says adding the mono one to path

### PR DESCRIPTION
**Pull request by bricelam**
Fixes #405

@anurse I can't seem to run the tests locally, so I 'm not sure if the one I wrote is correct. I manually verified that the product changes work, however.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Can you fix on Unix too?

**Comment by muratg** [comment]
@bricelam Brice, will you be able to add this to the .sh as well?

**Comment by bricelam** [comment]
@BrennanConroy @muratg That one might be a bit too far outside my area of expertise. :smile:

**Comment by BrennanConroy** [comment]
I'll take a stab at it and add a commit to this PR

**Comment by BrennanConroy** [comment]
@anurse Review please

**Comment by anurse** [comment]
Looks fine to me, but I don't have cycles for a full review. @BrennanConroy can give final sign-off.

**Comment by muratg** [comment]
@BrennanConroy assuming you tested the .sh change, :shipit:

**Comment by BrennanConroy** [comment]
@bricelam do you want to push or should I?

**Comment by bricelam** [comment]
I'll let you push.

**Comment by BrennanConroy** [comment]
03759863212ad1933e42348d93dd55943b0723d6

**Pull request closed without merging**
