### PR TITLE
Dnvm list displays friendly message when no runtimes found.

### LINKED ISSUE #380: Display a friendly message when dnvm list can find no runtimes
Currently it just returns. We should consider putting a message like `You don't have any runtimes installed. You can use dnvm install or dnvm upgrade commands` or something.

### PR DESCRIPTION
**Pull request by mholo65**
Fixes #380

### CODE REVIEW

**Comment by mholo65** [comment]
@anurse Was this how You imagined the test?

**Comment by anurse** [comment]
Indeed! Looks great. Thanks for the contribution!

**Comment by mholo65** [comment]
No problem, add some more "up-for-grabs", so that I'll have something to do on my spare time. :)

**Comment by anurse** [comment]
Sounds good! /cc @glennc @muratg @Eilon

**Pull request merged**
