### PR TITLE
Removed duplicate 'unstable' from dnvm help

### LINKED ISSUE #234: Duplicate "Unstable unstable" text in dnvm.sh help
Here:
https://github.com/aspnet/dnvm/blob/dev/src/dnvm.sh#L287-L296

Seems to be fine in the PS1 version.

@glennc

### PR DESCRIPTION
**Pull request by mholo65**
Fixes #234

### CODE REVIEW

**Comment by Eilon** [comment]
@BrennanConroy can you review and merge? And close the awesome bug I opened: #234 .

**Comment by mholo65** [comment]
@Eilon I got to admit, this was a tough one...

**Comment by BrennanConroy** [comment]
I don't know... that Travis CI failure is suspicious...

**Comment by Eilon** [comment]
:smile:

**Pull request merged**
