### PR TITLE
Add execute permissions for dnu after unpack

### PR DESCRIPTION
**Pull request by dennisburton**
#368

Add execute permissions for dnu as well as dnx.

### CODE REVIEW

**Comment by BrennanConroy** [comment]
Looks good, could you also remove line 258-260? #349

**Comment by dennisburton** [comment]
I'll see if I can dig a bit into why those lines did not work. In theory, if they worked neither dnx nor dnu should have to be modified directly.

**Comment by dennisburton** [comment]
After digging into those lines, it appears  the -r passed to xargs is valid in Linux but not OSX. 
[OSX man](https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/xargs.1.html)

Since the goal of -r is to ensure xargs does not run when the input is empty, I did some testing by removing dnu and dnx from the runtimes folder manually before running the script. In this case, chmod is not run since there are no matching shell script files. 

It seems like this PR should:

1. remove the -r option from the xargs call
1. remove lines 251-260 since both dnx and dnu are processed by the new 249-250

@BrennanConroy Is there any testing on this that would validate against different versions of Linux and OSX? I have only been able to test against OSX Yosmite and Ubuntu 14.10.

**Comment by BrennanConroy** [comment]
The issue I linked is about us wanting to remove the entire xargs section and only have the lines for dnx and dnu

Sent from my HTC

----- Reply message -----

**Comment by dennisburton** [comment]
Got it. I'll update and tag both

**Comment by BrennanConroy** [comment]
@glennc @anurse 
Could you squash commits?

**Comment by anurse** [comment]
:shipit: (once commits are squashed). @BrennanConroy can give final sign-off and merge.

**Comment by dennisburton** [comment]
@BrennanConroy do you want me to squash on the PR or are you talking about squashing on merge?

**Comment by BrennanConroy** [comment]
On the PR please :)

**Comment by BrennanConroy** [comment]
Looks great! Thank you for the contribution!

**Pull request merged**
