### PR TITLE
Fixed sorting in dnvm list on Linux

### LINKED ISSUE #334: [Linux] `dnvm list` should display installed runtimes in a reasonable order
Example scrambled output of `dnvm list` on Linux:
```
Active Version              Runtime Arch Location             Alias
------ -------              ------- ---- --------             -----
  *    1.0.0-beta6-12108    mono         ~/.dnx/runtimes      default
       1.0.0-beta6-11944    mono         ~/.dnx/runtimes
       1.0.0-beta5          coreclr x64  ~/.dnx/runtimes
       1.0.0-beta5-12103    coreclr x64  ~/.dnx/runtimes
       1.0.0-beta6-11941    mono         ~/.dnx/runtimes
       1.0.0-beta5          mono         ~/.dnx/runtimes
       1.0.0-beta4          mono         ~/.dnx/runtimes
       1.0.0-beta6-12108    coreclr x64  ~/.dnx/runtimes
       1.0.0-beta5-12103    mono         ~/.dnx/runtimes
       1.0.0-beta6-11923    mono         ~/.dnx/runtimes
```

### PR DESCRIPTION
**Pull request by mholo65**
Fixes #334 once again :)

c5307b1 broke it.

### CODE REVIEW

**Comment by dougbu** [comment]
LGTM. Tested it out on a Mint system and `dnvm list` was correctly sorted.

**Comment by mholo65** [comment]
//cc @anurse @BrennanConroy

**Comment by BrennanConroy** [comment]
Is this still a problem with the latest?

**Comment by mholo65** [comment]
As a matter of fact it isn't anymore. Global Install (fc63c6c) fixed this by separating runtimes with newline and adding -e option to the echo command while listing them.

Closing this PR.

**Pull request closed without merging**
