### PR TITLE
Dnvm list sort linux

### PR DESCRIPTION
**Pull request by mholo65**
Fixes issue #334

### CODE REVIEW

**Comment by dougbu** [comment]
Looks like the right fix for #334 but I defer to core team for actual squirrel.

**Comment by anurse** [comment]
Looks good to me, :shipit:. @BrennanConroy is our main DNVM guy right now, he can make the final merge decision.

**Comment by BrennanConroy** [comment]
This looks good, could you squash your commits and I'll merge

**Comment by mholo65** [comment]
Ok, hopefully I've done it right..

**Comment by BrennanConroy** [comment]
Noooo, take a look at this: http://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages
We want 1 commit for this PR

**Comment by mholo65** [comment]
Thanks! Now it should be fixed.

**Pull request merged**
